<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-H5MG9OP" failures="5" tests="14" name="TestNG_Concepts" time="22.382" errors="0" timestamp="2022-02-23T00:04:31 IST">
  <testcase classname="testNGConcepts.BasicTest" name="googleTitleTest" time="0.014"/>
  <testcase classname="testNGConcepts.BasicTest" name="googleLogo" time="0.047"/>
  <testcase classname="testNGConcepts.BasicTest" name="googleLinkText" time="0.016"/>
  <testcase classname="testNGConcepts.AssertTest" name="hardAssertCorrectValueTest" time="0.01"/>
  <testcase classname="testNGConcepts.AssertTest" name="hardAssertIncorrectValueTest" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [Goog] but found [Google]">
      <![CDATA[java.lang.AssertionError: expected [Goog] but found [Google]
at testNGConcepts.AssertTest.hardAssertIncorrectValueTest(AssertTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- hardAssertIncorrectValueTest -->
  <testcase classname="testNGConcepts.AssertTest" name="softAssertCorrectValueTest" time="0.002"/>
  <testcase classname="testNGConcepts.AssertTest" name="softAssertIncorrectValueTest" time="0.001">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Goog] but found [Google]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Goog] but found [Google]
at testNGConcepts.AssertTest.softAssertIncorrectValueTest(AssertTest.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- softAssertIncorrectValueTest -->
  <testcase classname="testNGConcepts.AssertTest" name="softAssertCorrectValueTestWithoutAssertAll" time="0.0"/>
  <testcase classname="testNGConcepts.AssertTest" name="softAssertIncorrectValueTestWithoutAssertAll" time="0.002"/>
  <testcase classname="testNGConcepts.ExceptionTest" name="invocationTest" time="5.017">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testNGConcepts.ExceptionTest.invocationTest() didn&amp;apos;t finish within the time-out 5000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testNGConcepts.ExceptionTest.invocationTest() didn't finish within the time-out 5000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- invocationTest -->
  <testcase classname="testNGConcepts.ExceptionTimeOutTest" name="testException" time="0.002">
    <failure type="java.lang.NumberFormatException" message="For input string: &amp;quot;100x&amp;quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: "100x"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.base/java.lang.Integer.parseInt(Integer.java:652)
at java.base/java.lang.Integer.parseInt(Integer.java:770)
at testNGConcepts.ExceptionTimeOutTest.testException(ExceptionTimeOutTest.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testException -->
  <testcase classname="testNGConcepts.ExceptionTimeOutTest" name="testExcludeException" time="0.001"/>
  <testcase classname="testNGConcepts.TestNGFeatureTest" name="dependsOnSource" time="0.002">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at testNGConcepts.TestNGFeatureTest.dependsOnSource(TestNGFeatureTest.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- dependsOnSource -->
  <testcase classname="testNGConcepts.TestNGFeatureTest" name="dependsOnTarget" time="0.0">
    <skipped/>
  </testcase> <!-- dependsOnTarget -->
</testsuite> <!-- TestNG_Concepts -->
