<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [TestNG Concepts Learning Suite]" guice-stage="DEVELOPMENT">
  <test thread-count="5" name="TestNG_Concepts(failed)">
    <classes>
      <class name="testNGConcepts.AssertTest">
        <methods>
          <include name="hardAssertIncorrectValueTest"/>
          <include name="softAssertIncorrectValueTest"/>
          <include name="afterSeperator"/>
          <include name="beforeSeperator"/>
        </methods>
      </class> <!-- testNGConcepts.AssertTest -->
      <class name="testNGConcepts.ExceptionTimeOutTest">
        <methods>
          <include name="testException"/>
        </methods>
      </class> <!-- testNGConcepts.ExceptionTimeOutTest -->
      <class name="testNGConcepts.TestNGFeatureTest">
        <methods>
          <include name="dependsOnTarget"/>
          <include name="dependsOnSource"/>
        </methods>
      </class> <!-- testNGConcepts.TestNGFeatureTest -->
      <class name="testNGConcepts.ExceptionTest">
        <methods>
          <include name="invocationTest"/>
        </methods>
      </class> <!-- testNGConcepts.ExceptionTest -->
    </classes>
  </test> <!-- TestNG_Concepts(failed) -->
</suite> <!-- Failed suite [TestNG Concepts Learning Suite] -->
